### ISSUE TITLE
[WIP] Recette staging 29/06/22 

### ISSUE THREAD

**Issue by mehdi-zaidi** [moussamew/killer-web#57]
- [ ] #115
<img width="100" alt="image" src="https://user-images.githubusercontent.com/34066687/176423471-5366ac34-5faf-4a01-98ff-a73d4f25d88b.png">

- [ ] Lors de l'ajout d'une mission, permettre l'ajout via la touche "Entrée"

**Comment by moussamew** [comment]
Issues #61 et #115 créer en référence à cette recette.

L'issue peut donc être fermé.
